package org.example.contactlink;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class ContactLinkController {

    @Autowired
    private VCardService vCardService;

    @GetMapping("/generate-vcard")
    public ResponseEntity<byte[]> generateVCard() {
        String vCard = vCardService.generateVCard("Stefan Djukic", "062890285", "stefan.dukic@unicreditgroup.ba","Stariji Specialista za aplikativnu podrsku",
                "UNICREDIT","/9j/4AAQSkZJRgABAQAAAQABAAD/4gHYSUNDX1BST0ZJTEUAAQEAAAHIAAAAAAQwAABtbnRyUkdCIFhZWiAH4AABAAEAAAAAAABhY3NwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAA9tYAAQAAAADTLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlkZXNjAAAA8AAAACRyWFlaAAABFAAAABRnWFlaAAABKAAAABRiWFlaAAABPAAAABR3dHB0AAABUAAAABRyVFJDAAABZAAAAChnVFJDAAABZAAAAChiVFJDAAABZAAAAChjcHJ0AAABjAAAADxtbHVjAAAAAAAAAAEAAAAMZW5VUwAAAAgAAAAcAHMAUgBHAEJYWVogAAAAAAAAb6IAADj1AAADkFhZWiAAAAAAAABimQAAt4UAABjaWFlaIAAAAAAAACSgAAAPhAAAts9YWVogAAAAAAAA9tYAAQAAAADTLXBhcmEAAAAAAAQAAAACZmYAAPKnAAANWQAAE9AAAApbAAAAAAAAAABtbHVjAAAAAAAAAAEAAAAMZW5VUwAAACAAAAAcAEcAbwBvAGcAbABlACAASQBuAGMALgAgADIAMAAxADb/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD/wAARCAAgACADASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAABggEBwkF/8QALBAAAgEEAgEDAwMFAQAAAAAAAQIDBAUGEQchEgAIMRMUIgkyURUWM0FCYf/EABgBAAIDAAAAAAAAAAAAAAAAAAYHBAUI/8QAJhEAAgEEAQQCAgMAAAAAAAAAAQIRAwQFIRIABjFBByIykdHw8f/aAAwDAQACEQMRAD8AQXhzhyPMYxkmSCRbSrlYYVJU1JU6Ylh2EBBHXZO+xrtv+HcJxK83ik4/uWa0WB4/UO8wnenLUi1BCgFkVlRWYKAZGYD8Rs/HoVpbVabHTx2awrMttoh9CkEzBpPor0nmQAC2gNnQ2dnXpp/Zb7chyLfl5LzK3+eM2WfVHBKv43CsXvsf9RRnRb/TNpewHHpe1bu4zV6KSbSdDYED2Y/vodaqssHi/jzt1ryv9a/HdQBS/MjSpyBGjoCIMS3s9WDXfpsY/keO/wBq5hyxcLxZ2kFR9kbYEgEoVlWVFMzeDhXcB10wDNojZ9Ij70/00qX2ucenkyx8xQ5BHPdFp1stRalopYqYo7PKkpqXMvgwjXx8B/kB3sANrhzpz7hvBWOm43yQVl2qkb+m2mKQCaqb+Se/CMH9zkdfADHSnLbnC/cge6CuudHfGN1veQJ9haaBJVhginZgaaCLzYLGgl8O2bvssx2T6Iqt5Z4d1tqI2xEiSQBPnZ89KeywGf79t62YyDDhTRyrcVUuwBIUcVEgHyTobA3Md7grj+H3IZ5Q23j96iLHrk7171c6KJKK3B+zIqsyiUbEfiGI+p1vW29PJzJ7j+O/bPjFNxhxzQUlffbbSrTUtvjbyp7euunqWB2XO/IpvzYklivkGOQPtc94mRe2vDcuxaxV9yhfLpqNJJ6eFXkoYYfq+TU7tIPpu/128vx3+ClWU9iwKDkzCMiX7+nzK3TSVDszfcVQjndt7YskhD73vsjv59VlxRq4VXFmhJY/lEwPQH8n/DDFX9j8h1qD565REoqIo8oLvH2diYEH0qkkDyRJk4y7L8lzvIKvKcuvE9zuda/nNPMe/wDxVA6VQOgqgADoAegbP8tmwfEbjklFcqi319PEVt9TSzGKeKrbqF4mBBDo2n2DsBCR8eo185SwDH6VqmsymgmK7AgpJlqJmYD9vghJUnWttofyR6W/lHlK48i3FESJqS0UjE0tL5bLN8GWQjouR8D4UdDe2ZoGJxNxd3ArVgQoMkn3+/M+z0Ud8d84rB4qpYY+orVmUoqoQQgIiTGlgeB5JjUSev/Z");
        byte[] vCardBytes = vCard.getBytes();

        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.TEXT_PLAIN);
        headers.setContentDispositionFormData("attachment", "contact.vcf");

        return ResponseEntity.ok().headers(headers).body(vCardBytes);
    }
}

